Pizzeria/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('pizzas.urls')),

]

pizzas/urls.py
from django.urls import path
from . import views
app_name= 'pizzas'

urlpatterns=[
    path('',views.index,name='index'),
    path('pizzas',views.pizzas,name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),
    path('comments/<int:pizza_id>/', views.comments, name='comments'),
    #path('<slug:slug>/', views.pizza_comment, name='pizza_comment'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name='users'
urlpatterns=[
    path('',include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

pizzas/models.py
from django.db import models

from django.contrib.auth.models import User


# Create your models here.

class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza=models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name= models.TextField()

    def __str__(self):
        return self.topping_name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True,blank=True)
    

    class Meta:
        ordering=['date_added']

    def __str__(self):
        return (self.text, self.name)
#'Comment {} by {}'.format

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from .models import *
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields= ('name', 'text')
        labels={'name': 'name', 'text': ''}


        

pizzas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import CommentForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas =Pizza.objects.all()

    context= {'all_pizzas':pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    p = Pizza.objects.get(id=pizza_id)

    toppings=Topping.objects.filter(pizza=p)

    context= {'pizza':p, 'toppings':toppings}
    return render(request, 'pizzas/pizza.html', context)

@login_required

def comments(request, pizza_id):
    form=CommentForm(data=request.POST)
    comments=Pizza.objects.get(id=pizza_id)
    comments = Comment.objects.all().filter(pizza=pizza_id)
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method == 'POST' and request.POST.get('btn1'):
        form= CommentForm()
        comment = request.POST.get('comment')
        Comment.objects.create(pizza_id=pizza_id,username=request.user, text=comment)
    else:
        form=CommentForm(data=request.POST)
        if form.is_valid():
            comments=form.save(commit=False)
            comments.pizza=pizza
            comments.save()
            return redirect('pizzas:index')

    context = {'pizza': pizza, 'form':form, 'comments':comments}

    return render(request, 'pizzas/comments.html', context)
'''
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comments = form.save(commit=False)
            comments.user_id = request.user
            comments.message= comments
            comments.save()
            return redirect('comments', pizza_id=pizza_id)
        else:
            form=CommentForm()
    return render(request, "pizzas/comments.html", {'pizza':pizza, 'form': form})

    template_name = 'pizza_comment.html'
    post = get_object_or_404(Pizza, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment= None

    if request.method == 'POST':
        comment_form=CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit= False)
            new_comment.post = post
            new_comment.save()
        else:
            comment_form = CommentForm()
        return render(request, template_name, {'post':post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})
def comments(request):
    if request.method == 'POST' and request.POST.get('btn1'):
        form= CommentForm()
        #comment = request.POST.get('comment')
        #Comment.objects.create(pizza_id=pizza_id,username=request.user, text=comment,date_added=date.today())
    #comments = Comment.objects.filter(pizza=pizza_id)
    #pizza = Pizza.objects.get(id=pizza_id)
    else:
        form=CommentForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('pizzas:index')

    context = {'pizza': pizza, 'comments':comments}

    return render(request, 'pizza/comments.html', context)'''

users/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm



# Create your views here.
def register(request):
    """Register as a new user to leave a comment on a Pizza."""
    if request.method != 'POST':
        form =UserCreationForm()
    else:
        form= UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user=form.save()
            login(request,new_user)
            return redirect('pizzas:index')

    context={'form':form}
    return render(request, 'registration/register.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href = "{% url 'pizzas:index' %}"> <font size='6'>Tall-ee's Pizza</font></a><br>
    <a href="{% url 'pizzas:pizzas' %}"> <font size='6'>Pizzas</font></a>
    {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
    <a href="{% url 'users:register' %}">Register</a>
        <a href="{% url 'users:login' %}">Log in</a>
        
    {% endif %}

</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/comments.html
{% extends 'pizzas/base.html' %}

{% block content %}

<body bgcolor="beige"></body>
<p><a href ="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>


<ul>
    <p>Comments</p>

        <p> {% for c in comments %}</p>

        <li>{{ c.text }}</li>

        {% endfor %}
</ul>
<p>Add a comment about a pizza:</p>
<form action=" " method="post"> {% csrf_token %}
    {{ form }}
    <p>{{response}}</p>
    <input type="submit" value="Submit" />
</form>



{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}


{% block content %}
<body bgcolor="lightblue"></body>
<font size="18"> Welcome to Tall-ee's</font>
<br><br><br>
<font size="6">We hope to provide you with the best pizzas with high quality
    ingredients. Find us in Waco, Texas. Ranked number 1 above Shorty's down the street! Travel through our page to find all of our options!</font>
<br><br>
<img src="https://img.cdn4dd.com/cdn-cgi/image/fit=contain,width=1200,height=672,format=auto/https://doordash-static.s3.amazonaws.com/media/photos/ba57d434-bbe9-48ad-9de8-cc5d539e83ca-retina-large.jpg"height="200px" width="200px">
<img src="https://www.papajohns.com/shaq/img/sar-hero.jpg"height="200px" width="200px">
<img src="https://food.fnr.sndimg.com/content/dam/images/food/fullset/2014/10/7/0/DV2103H_Shortys-Pizza-and-Smoked-Meat_s4x3.jpg.rend.hgtvcom.616.462.suffix/1412699454732.jpeg"height="200px" width="200px">
<br><br>


{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}


{% block content %}
<p> Pizza: {{ pizza }} </p>

<body bgcolor="lightgreen"></body>


<ul>
    <p>Toppings</p>
    {% for t in toppings %}


    <li><font size='4'>{{ t.topping_name}}</font></li>
  

    {% empty %}
    <li> No toppings have been added for this pizza.</li>

    {% endfor %}

    
    <p>       <font size="5">
        <a href="{% url 'pizzas:comments' pizza.id %}"> {{ pizza }} Comments</a></font>
      
    </p> 
</ul>


{% endblock content %}

pizzas/templates/pizzas/pizza_comment.html
{% extends 'base.html' %} {% block content %}

{% for comment in comments %}

<div class="comments" style="padding: 15px;">
<p class='font-weight-bold'>
    {{ comment.name }}
    <span class=" text-muted font-weight-normal">
        {{ comment.created_on }}

    </span></p>
    {{ comment.body | linebreaks }}

    </div>
    {{% endfor %}}
<div class="card-body">
    <h3>Leave a comment</h3>
    <form method="pizza" style="margin-top: 1.3em;">
        {{ comment_form.as_p}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">Submit Comment</button>

    
    </form>
</div>

pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}


{% block content %}
<p> <font size='4'>Pizzas </font></p>

<body bgcolor="lightyellow"></body>
<ul>
    {% for pizza in all_pizzas %}


    <li>
        <font size="5">
        <a href="{% url 'pizzas:pizza' pizza.id %}"> {{ pizza }} </a></font>
      
    </li>

    {% empty %}
    <li> No pizzas have been added yet.</li>

    {% endfor %}


{% endblock content %}
</ul>